source "https://rubygems.org"

gem "rake", "< 11.0.0"
gem "ruboty-replace"
gem "ruboty-bundler"
gem "ruboty-echo"
gem "ruboty-irasutoya", git: "git://github.com/june29/ruboty-irasutoya.git"
gem "ruboty-lgtm"
gem "ruboty-qiita_anti_spam"
gem "ruboty-qiita_police"
gem "ruboty-redis"
gem "ruboty-scorekeeper"
gem "ruboty-slack"
gem "ruboty-talk"
gem "ruboty-twitter_search"
gem "ruboty-ruby", ">= 0.0.2"
gem "ruboty-sushiyuki"
gem "ruboty-alias", "= 0.0.8"
gem "ruboty-cron", "= 1.0.1"
gem "ruboty-qiita-github", ">= 0.2.2"
gem "ruboty-jobcan", git: "git://github.com/uasi/ruboty-jobcan.git"
gem "ruboty-ruby_persistence", "= 0.2.0"
gem "increments-schedule", "= 0.15.0"