source "https://rubygems.org"

gem "rake"
gem "ruboty-replace"

gem "ruboty-alias"
gem "ruboty-cron"
gem "ruboty-delay"
gem "ruboty-echo"
gem "ruboty-github"
gem "ruboty-google_image"
gem "ruboty-karma"
gem "ruboty-redis"
gem "ruboty-reinvite"
gem "ruboty-ruby", ">= 0.0.2"
gem "ruboty-slack"
gem "ruboty-talk"
gem "ruboty-twitter_search"

gem "increments-schedule", "= 0.7.2"
