source "https://rubygems.org"

ruby "2.2.0"
gem "google-api-client", "= 0.8.2"
gem "rake"
gem "ruboty-replace"
gem "ruboty-bundler"
gem "ruboty-echo"
gem "ruboty-github"
gem "ruboty-google_calendar"
gem "ruboty-google_image"
gem "ruboty-lgtm"
gem "ruboty-qiita_police"
gem "ruboty-redis"
gem "ruboty-scorekeeper"
gem "ruboty-slack"
gem "ruboty-talk"
gem "ruboty-twitter_search"
gem "ruboty-ruby", ">= 0.0.2"
gem "ruboty-weather"
gem "ruboty-sushiyuki"
gem "ruboty-alias", "= 0.0.8"
gem "ruboty-cron", "= 1.0.1"
gem "increments-schedule", "= 0.7.0"
gem "xrc"
